{% set name = "jonmorton-haven" %}  # Renamed to avoid name conflict with https://pypi.org/project/haven/
{% set version = "0.0.1" %}
{% set python_min = "3.10.1" %}  # https://github.com/jonmorton/haven/blob/2e501f2db2557bf62cd69c86e2fac1b2280e5770/pyproject.toml#L19

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jonmorton/haven/archive/2e501f2db2557bf62cd69c86e2fac1b2280e5770.tar.gz
  sha256: a68233f72f57a7ba568fffd4cf1eb7504b229e630759bfc39cc9804128d3fd13

build:
  entry_points:
    - flit = flit:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - fsspec
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - haven
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jonmorton/haven
  summary: A simple, flexible library for configuring python projects using dataclasses.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
